title: Lucas Simões de Oliveira
description: Assessor de Investimentos - XP, Economista em formação - UFV
site_title: '@lsso - Lucas Simoes de oliveira'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: lsso
blog_url: https://www.nagekar.com
email: simoeslucasoliv@outlook.com
keybase_username: lsso
instagram_username: simoeslucasoliv@outlook.com

# absolute or relative
profile_picture: 

# Google Analytics ID
google_analytics: 